FROM mysql

ENV MYSQL_PASSWORD=testTrillianUserPwd \
    MYSQL_USER=testTrillianUser \
    MYSQL_DATABASE=testTrillianDB \
    MYSQL_RANDOM_ROOT_PASSWORD=yes

ADD storage/mysql/storage.sql /docker-entrypoint-initdb.d/storage.sql
